trigger:
  - '*'
pr:
- master

pool:
  vmImage: 'windows-latest'

variables:
  - group: 'Library'
  - name: ModuleName
    value: mms-azure
  - name: RepoName
    value: 'LocalFSRepo'
  - name: FailOnTestFailure
    value: false

resources:
  repositories:
    - repository: MMS-2024-Templates
      endpoint: github.com_mms
      type: github
      name: umn-microsoft-automation/MMS-2024-Templates

stages:
- template: PSModules/mms-module.yml@MMS-2024-Templates
  parameters:
    ModuleName: $(ModuleName)
    RepoPath: '$(RepoPath)'
    RepoName: $(RepoName)
    FailOnTestFailure: ${{ variables.FailOnTestFailure }}
